### ISSUE TITLE
Link to data pack does not work

### ISSUE THREAD

**Issue by sophiakene** [SIMPATICOProject/SimpaticoTAEServer#9]
Hi
This link: https://www.dcs.shef.ac.uk/people/C.Scarton/resources/ijcnlp2017_demo_data.tar.gz 
doesn't seem to work anymore.
Cheers

**Comment by carolscarton** [comment]
Hi

Please, use:
http://staffwww.dcs.shef.ac.uk/people/C.Scarton/resources/ijcnlp2017_demo_data.tar.gz

Our department has changed the links and I haven't had time to solve the the dependencies yet, sorry.

Cheers,
Carol

**Comment by sophiakene** [comment]
Thank you very much!
